# These are supported funding model platforms

github: [DeJayDev] 
patreon: # Soon?
open_collective: # Soon?
ko_fi: DeJayDev # Replace with a single Ko-fi username
custom: ['https://paypal.me/dejaydev', 'https://cash.app/$dejaydev']
